---
title: "Reports in R"
author: "Cornelius Tanui"
date: "`r Sys.Date()`"
output:
  html_document: default
  word_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      message = FALSE,
                      warning = FALSE)
```


```{r load scripts}

source("packages.R")

source("r_training_2.R")

```

## Summary Tables

```{r tab1}

(tab1 <- 
  STIData2 %>% 
  dplyr::group_by(CaseStatus, Sex) %>% 
  dplyr::summarise(`Mean Age` = round(mean(Age),1),
                   `Median Weight` = median(Weight),
                   `Max Height` = max(Height))%>% 
   DT::datatable())

```


```{r tab2}

(tab2 <- 
  STIData2 %>% 
  dplyr::group_by(Occupation, Sex) %>% 
  dplyr::summarise(MeanAge = round(mean(Age),1)) %>% 
  dplyr::ungroup()%>% 
  DT::datatable())

```

```{r graph1}

(graph1 <- 
  STIData2 %>% 
  ggplot2::ggplot(aes(x = Age,
                      y = Height,
                      color = CaseStatus)) + 
  ggplot2::geom_jitter())
  
```



